version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - run: sudo apt install yasm nasm
      - run: ./configure --prefix=$(pwd)/out && make && make install
      - run: cd out && tar -cvzf ../ffmpeg.tar . && cd .. && aws s3 cp ffmpeg.tar s3://wmg-deploy/ffmpeg.tar

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
